spring:
  application:
    name: User-Service #服务名称
  cloud:
    config:
      override-none: true
     
server:
  port: 8101 #端口号
  
sp:
  user-service:
    users: "[{\"id\":99, \"username\":\"sv\",\"password\":\"123\"},{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka #将服务注册到eureka中心
      
management:
  endpoints:
    web:
      exposure:
        include: refresh