spring:
  #配置消息总线
  rabbitmq:
    host: 192.168.126.140
    port: 5672
    username: admin
    password: root
  application:
    name: zuul
  cloud:
    config:
      override-none: true
    
    
server:
  port: 3001


  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true  #zuul开启重试 默认只有负载均衡没有重试, 需要加完整retry依赖  routes:    Order-Service: /order-service/**
    User-Service: /user-service/**
    Item-Service: /item-service/**
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream